//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ExperienceID { get; set; }
        public string ExperienceName { get; set; }
        public string ExperienceTestimonial { get; set; }
        public string ExperienceYear { get; set; }
    }
}
